// ReSharper disable InconsistentNaming
namespace NinjaOne_Api.Library.Enums;

public enum NodeClass
{
    WINDOWS_SERVER,
    WINDOWS_WORKSTATION,
    LINUX_WORKSTATION,
    MAC,
    ANDROID,
    APPLE_IOS,
    VMWARE_VM_HOST,
    VMWARE_VM_GUEST,
    HYPERV_VMM_HOST,
    HYPERV_VMM_GUEST,
    LINUX_SERVER,
    MAC_SERVER,
    CLOUD_MONITOR_TARGET,
    NMS_SWITCH,
    NMS_ROUTER,
    NMS_FIREWALL,
    NMS_PRIVATE_NETWORK_GATEWAY,
    NMS_PRINTER,
    NMS_SCANNER,
    NMS_DIAL_MANAGER,
    NMS_WAP,
    NMS_IPSLA,
    NMS_COMPUTER,
    NMS_VM_HOST,
    NMS_APPLIANCE,
    NMS_OTHER,
    NMS_SERVER,
    NMS_PHONE,
    NMS_VIRTUAL_MACHINE,
    NMS_NETWORK_MANAGEMENT_AGENT,
    APPLE_IPADOS
}